# Generated by Django 5.0.7 on 2024-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Imagen', models.ImageField(upload_to='portafolio/images/')),
                ('Url', models.URLField(blank=True)),
            ],
        ),
    ]
